server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://100.25.17.5:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - "localhost"
        labels:
          job: varlogs
          host: promtail-server
          __path__: /var/log/*log

  - job_name: nginx
    static_configs:
      - targets:
          - "localhost"
        labels:
          job: nginx
          host: promtail-server
          __path__: /var/log/nginx/*.log
