version: '3.9'
services:

  promtail:
    image: grafana/promtail:2.4.0
    restart: always
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml