global:
  resolve_timeout: 5m

route:
  receiver: "telegram-notifications"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m

receivers:
  - name: "telegram-notifications"
    telegram_configs:
      - bot_token:
        api_url: https://api.telegram.org
        chat_id:
        parse_mode: ""
