global:
  scrape_interval: 20s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /config/alertmanager.yml

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["54.227.168.102:9100"]
