groups:
  - name: AllInstances
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        annotations:
          title: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
        labels:
          severity: "critical"

      - alert: HighCPUUsage
        expr: avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) < 0.5
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "CPU usage is above 50% on instance {{ $labels.instance }}"
          summary: "High CPU Usage Alert"
