version: '3.9'
services:

  promtail:
    image: grafana/promtail:2.9.2
    restart: always
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
    depends_on: 
      - nginx
  
  nginx:
    image: nginx:stable-alpine3.20
    restart: always
    volumes: 
      - ./nginx-files/:/var/www/html/
      - ./nginx-files/configs:/etc/nginx
    ports:
      - "80:80"

  node_exporter: 
    image: prom/node-exporter:v1.8.2
    ports:
      - 9100:9100
    depends_on:
      - nginx
