version: '3.9'
services:

  loki:
    image: grafana/loki:latest
    restart: always
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/data:/loki
      - ./configs/loki/loki.yml:/etc/loki/loki.yml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:main
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:main
    restart: unless-stopped
    volumes: 
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
volumes:
  prometheus_data: