{
 "title": "Prometheus metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg without(cpu)(irate(node_cpu_seconds_total{job=\"node\", instance=\"3.90.83.194:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Total memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"3.90.83.194:9100\", job=\"node\"} - node_memory_MemFree_bytes{instance=\"3.90.83.194:9100\", job=\"node\"} - node_memory_Cached_bytes{instance=\"3.90.83.194:9100\", job=\"node\"} - node_memory_Buffers_bytes{instance=\"3.90.83.194:9100\", job=\"node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"3.90.83.194:9100\", job=\"node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"3.90.83.194:9100\", job=\"node\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"3.90.83.194:9100\", job=\"node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"3.90.83.194:9100\", job=\"node\"} - node_memory_MemFree_bytes{instance=\"3.90.83.194:9100\", job=\"node\"}) / node_memory_MemTotal_bytes{instance=\"3.90.83.194:9100\", job=\"noe\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"3.90.83.194:9100\", job=\"node\"} / node_memory_MemTotal_bytes{instance=\"3.90.83.194:9100\", job=\"node\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"3.90.83.194:9100\", job=\"node\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"3.90.83.194:9100\", job=\"node\"}[5m])",
     "legendFormat": "{{device}} transimit"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"3.90.83.194:9100\", job=\"node\", device!~\"tmpfs | nsfs\", device!~\"/dev/loop\", device!~\"gvsd_fuse\"} - node_filesystem_avail_bytes{instance=\"3.90.83.194:9100\", job=\"node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Avail Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"3.90.83.194:9100\", job=\"node\", device!~\"tmpfs | nsfs\", device!~\"/dev/loop\", device!~\"gvsd_fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}