---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    allow_downgrade: yes

- name: Create Nginx directory
  ansible.builtin.file:
    path: "{{ nginx_custom_directory }}"
    state: directory

- name: Copy web files to the host
  ansible.builtin.copy:
    src: ./templates/web/
    dest: "{{ nginx_custom_directory }}"
    mode: "0644"
    remote_src: no
  notify: Restart Nginx

- name: Ensure Nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
