---
- name: Check if Docker is installed
  command: docker -v
  register: docker_installed
  ignore_errors: true

- name: Check if Docker Compose is installed
  command: docker-compose -v
  register: docker_compose_installed
  ignore_errors: true

- name: Update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Install other tools
  apt:
    name:
      - apt-transport-https
      - apache2-utils
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: docker_installed.failed

- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_installed.failed

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  when: docker_installed.failed

- name: Create Docker group
  group:
    name: docker
    state: present
  when: docker_installed.failed

- name: Create Docker user
  user:
    name: docker
    groups: docker
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: true
    cache_valid_time: 35000
  when: docker_installed.failed
  notify: Restart Docker

- name: Add current user to Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  when: docker_installed.failed

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0755"
  when: docker_compose_installed.failed
