---
- name: Setup web-site
  hosts: website
  become: true
  roles:
    - nginx
    - node-exporter

- name: Setup monitoring
  hosts: monitor
  become: true
  roles:
    - docker

- name: Setup promtail
  hosts: website
  become: true
  roles:
    - promtail
